### PR TITLE
Spotlight support to initialize with UIView

### PR DESCRIPTION
**Pull request by koutalou**
### What

* Spotlight support to initialize with UIView and margin

#### Example

`Spotlight(shape: .OvalWV(center: targetOvalView, margin: 5))`
`Spotlight(shape: .RoundedRectWV(center: targetRoundedView, radius: 10, margin: 10)`

##### Sample example project code

* https://github.com/koutalou/Gecco/tree/sample-init-with-view

#### Sample gif

gecco_init_with_view

### CODE REVIEW

**Comment by yukiasai** [comment]
@koutalou Please submit a PR to feature/calculate_position_from_view branch!

**Comment by koutalou** [comment]
Thank you for replying.
OK, I will submit this to feature/calculate_position_from_view branch.

**Comment by koutalou** [comment]
I made new PR, please review.
https://github.com/yukiasai/Gecco/pull/14

**Comment by yukiasai** [comment]
thx!

**Pull request closed without merging**
